server.port: 9093
spring:
  application.name: booking-financial-service
  datasource:
    url: jdbc:postgresql://localhost:5434/booking
    username: postgres
    password: javaec2023
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin.base-url: http://localhost:9411/
  kafka:
    bootstrap-servers: 127.0.0.1:29092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  security:
    enabled: false
#  server:
#    address: localhost
#    port: 6060
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  metrics:
    enable.jvm: true
