server:
  port: 9092
spring:
  application:
    name: booking-room-service
  datasource:
    url: jdbc:postgresql://localhost:5433/booking
    username: user
    password: javaec2023
  zipkin:
    base-url: http://localhost:9411/
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 15MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka
    fetch-registry: true
    register-with-eureka: true