server.port: 9092
spring:
  application:
    name: booking-room-service
  datasource:
    url: jdbc:postgresql://localhost:5433/booking
    username: user
    password: javaec2023
  zipkin:
    base-url: http://localhost:9411/
  kafka:
    bootstrap-servers: 127.0.0.1:29092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka
    fetch-registry: true
    register-with-eureka: true
