server:
  port: 5002
spring:
  profiles:
    active: "dev"
  application:
    name: SYLLABUS
  datasource:
    url: jdbc:postgresql://localhost:5432/fams
    username: java05
    password: password
  zipkin:
    base-url: http://localhost:9411/
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 15MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true