version: 2.1

jobs:
  analyze:
    docker:
      - image: 'cimg/openjdk:11.0-node'
    steps:
      - checkout
      - run:
          name: test and analyze on Sonar
          command: mvn test sonar:sonar
executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:11.0-node'
orbs:
  maven: circleci/maven@1.4.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk
#          filters:
#            branches:
#              only:
#                - main
      - analyze:
          context: SonarCloud
