version: 2.1

jobs:
  build:
#    docker:
#      - image: 'cimg/openjdk:11.0-node'
#    steps:
#      - checkout
#      - run:
#          name: test and analyze on Sonar
#          command: mvn test sonar:sonar

    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - run: mvn test sonar:sonar
#executors:
#  jdk:
#    docker:
#      - image: 'cimg/openjdk:11.0-node'
#orbs:
#  maven: circleci/maven@1.4.1
workflows:
  maven_test:
    jobs:
      - build
#      - maven/test:
#          executor: jdk
#          filters:
#            branches:
#              only:
#                - main
#      - analyze:
#          context: SonarCloud
