version: '3.8'
services:
  booking-user-postgresql:
    image: postgres:14.5
    volumes:
      - ~/volumes/bookingapp-user/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=javaec2023
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "127.0.0.1:5432:5432"
    expose:
      - "5432"
    restart: unless-stopped

  booking-room-postgresql:
    image: postgres:14.5
    volumes:
      - ~/volumes/bookingapp-room/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=javaec2023
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5433:5433"
    expose:
      - "5433"
    restart: unless-stopped

  booking-financial-postgresql:
    image: postgres:14.5
    volumes:
      - ~/volumes/bookingapp-financial/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=javaec2023
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5434:5434"
    expose:
      - "5434"
    restart: unless-stopped
