version: '3.8'
services:
  booking-user-postgresql:
    image: postgres:14.5
    volumes:
      - pg-user:/var/lib/postgresql/data
      - ../sql/init.user.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=javaec2023
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped

  booking-room-postgresql:
    image: postgres:14.5
    volumes:
      - pg-room:/var/lib/postgresql/data
      - ../sql/init.room.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=javaec2023
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5433:5432"
    restart: unless-stopped

  booking-financial-postgresql:
    image: postgres:14.5
    volumes:
      - pg-fin:/var/lib/postgresql/data
      - ../sql/init.financial.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=javaec2023
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5434:5432"
    restart: unless-stopped

volumes:
  pg-user:
    driver: local
  pg-room:
    driver: local
  pg-fin:
    driver: local
