version: '3.8'
services:
  zipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ~/volumes/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  zookeeper:
    image: zookeeper:3.8.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka-zero:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "29097:29097"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-zero:9009,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: "29097"
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka-zero -Dcom.sun.management.jmxremote.rmi.port=29097

  kafka-tool:
    image: provectuslabs/kafka-ui:v0.6.1
    depends_on:
      - kafka-zero
    ports:
    - "29093:29093"
    environment:
      KAFKA_CLUSTERS_0_NAME: booking-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-zero:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
#        KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
#        KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
#        KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083
