version: '3.8'
services:
  bookingapp-prometheus:
    image: prom/prometheus:v2.43.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "6060:9090"
    # network_mode: 'host' # doesn't work on VDI for some reason
    restart: unless-stopped

  bookingapp-grafana:
    image: grafana/grafana-oss:9.2.15
    volumes:
      - ./grafana/:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - "3000:3000"
    depends_on:
      - bookingapp-prometheus
    # grafana/provisioning/datasources/datasource.yml
    # network_mode: 'host'
    restart: unless-stopped
