server.port: 9091
spring:
  application:
    name: booking-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: javaec2023
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411/
  kafka:
    bootstrap-servers: 127.0.0.1:29092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
