global:
  scrape_interval: 15s # default
  evaluation_interval: 15s # default
  scrape_timeout: 10s # default

scrape_configs:
  - job_name: 'booking-prometheus'

    scrape_interval: 10s

    # scheme: https
    basic_auth:
      username: admin
      password: admin
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:9091' ]
        labels:
          application: 'Booking User Service'
      - targets: [ 'localhost:9092' ]
        labels:
          application: 'Booking Room Service'
      - targets: [ 'localhost:9093' ]
        labels:
          application: 'Booking Financial Service'
