global:
  scrape_interval: 15s # default
  evaluation_interval: 15s # default
  scrape_timeout: 10s # default

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'booking-prometheus'
    #    basic_auth:
    #      username: admin
    #      password: admin
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9876' ]
        labels:
          application: 'booking-eurekaserver'
      - targets: [ 'host.docker.internal:19090' ]
        labels:
          application: 'booking-apigw'
      - targets: [ 'host.docker.internal:19091' ]
        labels:
          application: 'booking-user-service'
      - targets: [ 'host.docker.internal:19092' ]
        labels:
          application: 'booking-room-service'
      - targets: [ 'host.docker.internal:19093' ]
        labels:
          application: 'booking-financial-service'

#  - job_name: 'system'
#    static_configs:
#      - targets: [ 'host.docker.internal:9101' ]
