server:
  port: 9090
spring:
  application:
    name: booking-api-gateway
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 0.5
  cloud:
    gateway:
      routes:
        # TODO: define routes
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka
    fetch-registry: true
    register-with-eureka: true