name: Maven CI

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"
    types: [opened, synchronize, closed]

jobs:
  test:
    if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Perform Maven commands
        run: mvn clean test
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions on ${{github.repository}} is ${{job.status}}
          # Required recipients' addresses:
          to: skywalker2834@gmail.com, notthienng@gmail.com
          # Required sender full name
          from: ThienNT14
          body: Job ${{github.job}} in workflow ${{github.workflow}} of repo ${{github.repository}} triggered by ${{github.actor}} is ${{job.status}}.
          ignore_cert: true
          convert_markdown: true
          priority: normal
